# Define the goal
# timeout < 0 will disable timeout
# hotwords have to be chosen from ["bambam", "cancel", "ready"]. Multiple hotwords can be given.
# if nothing is given, all hotword is detectable.
float32 timeout
string[] hotwords
---
# Define the result
bool succeeded
string hotword
---
# Define a feedback message
